# Generated by Django 4.0 on 2022-01-03 04:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0003_rename_description_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 10, 24, 32, 742061)),
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.URLField()),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='socialmedia.post')),
            ],
        ),
    ]
