# Generated by Django 4.0 on 2022-01-03 05:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0004_alter_post_created_at_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='socialmedia.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 10, 31, 17, 597010)),
        ),
    ]
