# Generated by Django 4.0 on 2022-01-04 06:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_birthdate_alter_user_location_and_more'),
        ('socialmedia', '0006_alter_comment_post_alter_like_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 4, 11, 31, 3, 538024)),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.user'),
        ),
    ]
