# Generated by Django 4.0.1 on 2022-01-05 16:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialmedia', '0010_remove_post_is_shared_remove_post_shared_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='date_confirmed',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='userid',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 22, 20, 58, 632257)),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=datetime.datetime.now)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_request_from', to=settings.AUTH_USER_MODEL)),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_request_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
