# Generated by Django 4.0.1 on 2022-01-05 16:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialmedia', '0012_friend_account_id_1_friend_account_id_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='account_id_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_account_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friend',
            name='account_id_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_account_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 22, 24, 39, 434841)),
        ),
    ]
