# Generated by Django 4.0.1 on 2022-01-05 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0013_alter_friend_account_id_1_alter_friend_account_id_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='date_confirmed',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 22, 29, 57, 663513)),
        ),
    ]
