# Generated by Django 4.0.1 on 2022-01-07 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0017_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 8, 0, 13, 1, 437247)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 8, 0, 13, 1, 435247)),
        ),
    ]
