# Generated by Django 4.0.1 on 2022-02-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0022_alter_comment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporayImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
